export const MESSAGE_TYPE = {
    'conversation': 'text',
    'extendedTextMessage': 'text',
    'pinInChatMessage': 'pin',
    'CALL_MISSED_VOICE': 'voiceCall',
    'CALL_MISSED_VIDEO': 'videoCall',
    'editedMessage': 'text',
    'listMessage': 'list',
    'templateMessage': 'button',
    'buttonsMessage': 'button',
    'templateButtonReplyMessage': 'replyButton',
    'audioMessage': 'audio',
    'imageMessage': 'image',
    'gifPlayback': 'gif',
    'videoMessage': 'video',
    'stickerMessage': 'sticker',
    'documentMessage': 'document',
    'documentWithCaptionMessage': 'document',
    'contactMessage': 'contact',
    'locationMessage': 'location',
    'reactionMessage': 'reaction',
    'productMessage': 'product',
    // 'viewOnceMessage': 'viewOnce',
    // 'viewOnceMessageV2': 'viewOnce',
    // 'viewOnceMessageV2Extension': 'viewOnce',
    'pollCreationMessage': 'poll',
    'pollCreationMessageV3': 'poll',
};